"""Init

Revision ID: 09868c6cd902
Revises: d75879e1b356
Create Date: 2024-01-15 01:19:05.072708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09868c6cd902'
down_revision: Union[str, None] = 'd75879e1b356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags_to_posts', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('tags_to_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tags_to_posts', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags_to_posts', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tags_to_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tags_to_posts', 'id')
    # ### end Alembic commands ###
