<<<<<<<< Updated upstream:ms/versions/3332c3e2907f_plus2.py
"""plus2

Revision ID: 3332c3e2907f
Revises: e5252d2ff9f6
Create Date: 2024-01-13 16:57:13.855020
========
"""3

Revision ID: 238434368199
Revises: 6c756b7ba4d7
Create Date: 2024-01-18 17:09:32.009411
>>>>>>>> Stashed changes:migrations/versions/238434368199_3.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< Updated upstream:ms/versions/3332c3e2907f_plus2.py
revision: str = '3332c3e2907f'
down_revision: Union[str, None] = 'e5252d2ff9f6'
========
revision: str = '238434368199'
down_revision: Union[str, None] = '6c756b7ba4d7'
>>>>>>>> Stashed changes:migrations/versions/238434368199_3.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
