"""Init

Revision ID: 24eef7241543
Revises: c62b18db795a
Create Date: 2024-01-12 23:52:57.644689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24eef7241543'
down_revision: Union[str, None] = 'c62b18db795a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_to_posts_post_id_fkey', 'tags_to_posts', type_='foreignkey')
    op.drop_constraint('tags_to_posts_tag_id_fkey', 'tags_to_posts', type_='foreignkey')
    op.drop_column('tags_to_posts', 'post_id')
    op.drop_column('tags_to_posts', 'tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags_to_posts', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tags_to_posts', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tags_to_posts_tag_id_fkey', 'tags_to_posts', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('tags_to_posts_post_id_fkey', 'tags_to_posts', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
