"""Init

Revision ID: 61d748bb4f7d
Revises: 17a90d03a7bc
Create Date: 2024-01-19 09:58:00.304107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d748bb4f7d'
down_revision: Union[str, None] = '17a90d03a7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_id', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'image_id')
    # ### end Alembic commands ###
