"""F3

Revision ID: 68883f65768f
Revises: 6edae488d0e0
Create Date: 2024-01-20 19:49:52.070477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68883f65768f'
down_revision: Union[str, None] = '6edae488d0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments_to_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments_to_posts', 'comment_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments_to_posts', 'comment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('comments_to_posts', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
