<<<<<<<< Updated upstream:ms/versions/861d705e302f_pl3.py
"""pl3

Revision ID: 861d705e302f
Revises: 3332c3e2907f
Create Date: 2024-01-13 18:35:49.309662
========
"""2

Revision ID: 6c756b7ba4d7
Revises: e30651539906
Create Date: 2024-01-18 16:58:46.931651
>>>>>>>> Stashed changes:migrations/versions/6c756b7ba4d7_2.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< Updated upstream:ms/versions/861d705e302f_pl3.py
revision: str = '861d705e302f'
down_revision: Union[str, None] = '3332c3e2907f'
========
revision: str = '6c756b7ba4d7'
down_revision: Union[str, None] = 'e30651539906'
>>>>>>>> Stashed changes:migrations/versions/6c756b7ba4d7_2.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
