"""Init

Revision ID: 713e80d2342e
Revises: 3d7d3d46e78b
Create Date: 2024-01-15 01:54:57.666569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713e80d2342e'
down_revision: Union[str, None] = '3d7d3d46e78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags_to_posts', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags_to_posts', 'id')
    # ### end Alembic commands ###
