"""Init

Revision ID: a5b9b5df9913
Revises: 04d2ebe2d8a7
Create Date: 2024-01-13 20:20:11.080303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b9b5df9913'
down_revision: Union[str, None] = '04d2ebe2d8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.alter_column('posts', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
