"""Init

Revision ID: b049f9875e73
Revises: 24eef7241543
Create Date: 2024-01-13 00:01:49.549028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b049f9875e73'
down_revision: Union[str, None] = '24eef7241543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags_to_posts', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('tags_to_posts', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tags_to_posts', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'tags_to_posts', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_to_posts', type_='foreignkey')
    op.drop_constraint(None, 'tags_to_posts', type_='foreignkey')
    op.drop_column('tags_to_posts', 'tag_id')
    op.drop_column('tags_to_posts', 'post_id')
    # ### end Alembic commands ###
